const { app, BrowserWindow, dialog, ipcMain, protocol, shell, session } = require('electron');
const { spawn } = require('child_process');
const crypto = require('crypto');
const fs = require('fs/promises');
const net = require('net');
const path = require('path');

let autoUpdater = null;
try {
  ({ autoUpdater } = require('electron-updater'));
} catch {
  autoUpdater = null;
}

const DEFAULT_APP_URL = 'http://localhost:3000';
const APP_PROTOCOL = 'app';
// Normally derived from packaging. The override lets an unpackaged binary
// exercise the production load path — app:// plus the CSP and navigation rules
// that ride on it — without a full `npm run dist`, which end-to-end tests and
// local debugging both need.
const isDev = process.env.RAG_FORCE_PACKAGED === 'true' ? false : !app.isPackaged;
const devAppUrl = process.env.RAG_DESKTOP_URL || process.env.NEXT_PUBLIC_APP_URL || DEFAULT_APP_URL;
// Next's static export injects inline hydration scripts. Without an allowlist
// the CSP blocks them and React never hydrates, leaving an inert window. The
// hashes are regenerated by scripts/generate-csp-hashes.js after every build,
// so only those exact scripts run rather than opening up 'unsafe-inline'.
let inlineScriptHashes = [];
try {
  inlineScriptHashes = require('./csp-hashes.json');
} catch {
  console.warn('[csp] csp-hashes.json missing; run `npm run build` to regenerate.');
}

const CSP = [
  "default-src 'self' app://local",
  ["script-src 'self' app://local", ...inlineScriptHashes].join(' '),
  "style-src 'self' app://local 'unsafe-inline'",
  "img-src 'self' app://local data:",
  "font-src 'self' app://local data:",
  "connect-src 'self' app://local http://127.0.0.1:* http://localhost:*",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
].join('; ');

let backendProcess = null;
let backendBaseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8000';
let backendToken = null;
let mainWindow = null;

protocol.registerSchemesAsPrivileged([
  {
    scheme: APP_PROTOCOL,
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      corsEnabled: true,
    },
  },
]);

function getAppUrl() {
  if (process.env.RAG_DESKTOP_URL || process.env.NEXT_PUBLIC_APP_URL) {
    return process.env.RAG_DESKTOP_URL || process.env.NEXT_PUBLIC_APP_URL;
  }

  return isDev ? DEFAULT_APP_URL : `${APP_PROTOCOL}://local/index.html`;
}

function getStaticRoot() {
  return path.join(__dirname, '..', 'out');
}

function isTrustedSender(event) {
  const url = event.senderFrame?.url || '';
  return url.startsWith(`${APP_PROTOCOL}://local`) || (isDev && url.startsWith(devAppUrl));
}

function getContentType(filePath) {
  const extension = path.extname(filePath).toLowerCase();
  const contentTypes = {
    '.css': 'text/css',
    '.html': 'text/html',
    '.ico': 'image/x-icon',
    '.js': 'text/javascript',
    '.json': 'application/json',
    '.png': 'image/png',
    '.svg': 'image/svg+xml',
    '.txt': 'text/plain',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
  };

  return contentTypes[extension] || 'application/octet-stream';
}

async function resolveStaticPath(url) {
  const requestUrl = new URL(url);
  const requestedPath = decodeURIComponent(requestUrl.pathname);
  const relativePath = requestedPath === '/' ? 'index.html' : requestedPath.slice(1);
  const staticRoot = getStaticRoot();
  const filePath = path.normalize(path.join(staticRoot, relativePath));

  if (!filePath.startsWith(staticRoot)) {
    throw new Error('Blocked invalid asset path');
  }

  return filePath;
}

function registerAppProtocol() {
  protocol.handle(APP_PROTOCOL, async (request) => {
    try {
      const filePath = await resolveStaticPath(request.url);
      const data = await fs.readFile(filePath);
      return new Response(data, {
        headers: {
          'content-security-policy': CSP,
          'content-type': getContentType(filePath),
        },
      });
    } catch {
      const fallback = path.join(getStaticRoot(), 'index.html');
      const data = await fs.readFile(fallback);
      return new Response(data, {
        headers: {
          'content-security-policy': CSP,
          'content-type': 'text/html',
        },
      });
    }
  });
}

function findAvailablePort() {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      server.close(() => resolve(address.port));
    });
  });
}

function getBackendCommand() {
  if (process.env.RAG_BACKEND_COMMAND) {
    return {
      command: process.env.RAG_BACKEND_COMMAND,
      args: process.env.RAG_BACKEND_ARGS ? process.env.RAG_BACKEND_ARGS.split(' ') : [],
      cwd: process.cwd(),
    };
  }

  if (isDev) {
    const backendDir = path.join(__dirname, '..', '..', 'backend');
    return {
      command: process.env.PYTHON || 'python3',
      args: ['-m', 'rag_backend'],
      cwd: backendDir,
      // Run from source without requiring an editable install.
      pythonPath: path.join(backendDir, 'src'),
    };
  }

  const executable = process.platform === 'win32' ? 'rag-backend.exe' : 'rag-backend';
  return {
    command: path.join(process.resourcesPath, 'backend', 'rag-backend', executable),
    args: [],
    cwd: path.join(process.resourcesPath, 'backend', 'rag-backend'),
  };
}

async function waitForBackend(timeoutMs = 30000) {
  const startedAt = Date.now();

  while (Date.now() - startedAt < timeoutMs) {
    try {
      const response = await fetch(`${backendBaseUrl}/health`, {
        headers: backendToken ? { Authorization: `Bearer ${backendToken}` } : {},
      });
      if (response.ok) return;
    } catch {
      // Keep polling until the sidecar opens the selected port.
    }

    await new Promise((resolve) => setTimeout(resolve, 500));
  }

  throw new Error('Backend did not become healthy before timeout');
}

async function startBackend() {
  if (process.env.RAG_START_BACKEND === 'false') return;

  const port = await findAvailablePort();
  backendBaseUrl = `http://127.0.0.1:${port}`;
  backendToken = crypto.randomBytes(32).toString('hex');
  const userDataPath = app.getPath('userData');

  const backend = getBackendCommand();
  backendProcess = spawn(backend.command, backend.args, {
    cwd: backend.cwd,
    env: {
      ...process.env,
      ENV: 'production',
      HOST: '127.0.0.1',
      PORT: String(port),
      WORKERS: '1',
      RAG_API_TOKEN: backendToken,
      APP_DATA_DIR: userDataPath,
      APP_DB_PATH: path.join(userDataPath, 'app.db'),
      CHROMA_PATH: path.join(userDataPath, 'vector', 'chroma'),
      ALLOWED_ORIGINS: `${APP_PROTOCOL}://local,${devAppUrl}`,
      PYTHONUNBUFFERED: '1',
      ...(backend.pythonPath ? { PYTHONPATH: backend.pythonPath } : {}),
    },
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  backendProcess.on('exit', (code, signal) => {
    backendProcess = null;
    if (code !== 0 && signal !== 'SIGTERM') {
      console.error(`RAG backend exited with code ${code || 'unknown'}`);
    }
  });

  backendProcess.on('error', (error) => {
    console.error(`Failed to start RAG backend: ${error.message}`);
  });

  backendProcess.stderr.on('data', (chunk) => {
    console.error(`[rag-backend] ${chunk.toString().trim()}`);
  });

  await waitForBackend();
}

function stopBackend() {
  if (!backendProcess) return;

  backendProcess.kill('SIGTERM');
  setTimeout(() => {
    if (backendProcess) backendProcess.kill('SIGKILL');
  }, 5000).unref();
}

// streamId -> AbortController for in-flight streaming queries.
const activeStreams = new Map();

function registerApiProxy() {
  ipcMain.handle('api:request', async (event, request) => {
    if (!isTrustedSender(event)) {
      return { ok: false, status: 403, error: 'Untrusted IPC sender' };
    }

    const method = request?.method || 'GET';
    const requestPath = request?.path;

    if (!['GET', 'POST', 'DELETE'].includes(method) || typeof requestPath !== 'string' || !requestPath.startsWith('/')) {
      return { ok: false, status: 400, error: 'Invalid API request' };
    }

    let response;
    try {
      response = await fetch(`${backendBaseUrl}${requestPath}`, {
        method,
        headers: {
          'Content-Type': 'application/json',
          ...(backendToken ? { Authorization: `Bearer ${backendToken}` } : {}),
        },
        body: request.body === undefined ? undefined : JSON.stringify(request.body),
      });
    } catch (error) {
      // The sidecar may not have started, or may have crashed. Rejecting here
      // would leave the renderer awaiting a promise that never settles.
      return { ok: false, status: 0, error: `Backend unreachable: ${error.message}` };
    }

    const text = await response.text();
    let data;
    try {
      data = text ? JSON.parse(text) : undefined;
    } catch {
      data = undefined;
    }

    return {
      ok: response.ok,
      status: response.status,
      data,
      error: response.ok ? undefined : data?.detail || text || 'API request failed',
    };
  });

  // Streaming queries cannot use api:request, which resolves only once the
  // whole response is buffered. Main owns the connection and the backend token;
  // the renderer receives frames through a per-stream channel it never names.
  // Streaming endpoints the renderer may open. An allowlist rather than a
  // free-form path keeps the bridge as narrow as the non-streaming one.
  const STREAM_ENDPOINTS = {
    query: '/query/stream',
    chat: '/chat/stream',
  };

  ipcMain.handle('api:openStream', async (event, request) => {
    if (!isTrustedSender(event)) {
      return { ok: false, error: 'Untrusted IPC sender' };
    }

    const path = STREAM_ENDPOINTS[request?.endpoint];
    if (!path) {
      return { ok: false, error: 'Unknown stream endpoint' };
    }
    if (!request?.body || typeof request.body !== 'object') {
      return { ok: false, error: 'Invalid request body' };
    }

    const streamId = crypto.randomUUID();
    const channel = `api:stream:${streamId}`;
    const controller = new AbortController();
    activeStreams.set(streamId, controller);

    const send = (frame) => {
      // The window can close mid-stream; sending to a destroyed frame throws.
      if (!event.sender.isDestroyed()) event.sender.send(channel, frame);
    };

    (async () => {
      try {
        const response = await fetch(`${backendBaseUrl}${path}`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Accept: 'text/event-stream',
            ...(backendToken ? { Authorization: `Bearer ${backendToken}` } : {}),
          },
          body: JSON.stringify(request.body),
          signal: controller.signal,
        });

        if (!response.ok || !response.body) {
          send({ event: 'error', code: 'retrieval_failed', error: `Backend returned ${response.status}` });
          return;
        }

        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let buffer = '';

        for (;;) {
          const { done, value } = await reader.read();
          if (done) break;

          buffer += decoder.decode(value, { stream: true });

          // SSE frames are separated by a blank line; a chunk may split one.
          let boundary = buffer.indexOf('\n\n');
          while (boundary !== -1) {
            const frame = buffer.slice(0, boundary);
            buffer = buffer.slice(boundary + 2);
            for (const line of frame.split('\n')) {
              if (!line.startsWith('data: ')) continue;
              try {
                send(JSON.parse(line.slice(6)));
              } catch {
                // Ignore a frame we cannot parse rather than killing the stream.
              }
            }
            boundary = buffer.indexOf('\n\n');
          }
        }
      } catch (error) {
        if (error.name === 'AbortError') {
          send({ event: 'error', code: 'cancelled', error: 'Generation cancelled' });
        } else {
          send({ event: 'error', code: 'internal_error', error: error.message });
        }
      } finally {
        activeStreams.delete(streamId);
        send({ event: 'closed' });
      }
    })();

    return { ok: true, streamId };
  });

  ipcMain.handle('api:cancelStream', (event, streamId) => {
    if (!isTrustedSender(event) || typeof streamId !== 'string') return false;
    const controller = activeStreams.get(streamId);
    if (!controller) return false;
    controller.abort();
    activeStreams.delete(streamId);
    return true;
  });

  ipcMain.handle('files:selectDocuments', async (event) => {
    if (!isTrustedSender(event)) {
      return [];
    }

    const result = await dialog.showOpenDialog({
      properties: ['openFile', 'multiSelections'],
      filters: [
        { name: 'Documents', extensions: ['pdf', 'docx', 'txt', 'md', 'markdown', 'html', 'htm'] },
      ],
    });

    return result.canceled ? [] : result.filePaths;
  });
}

function createWindow() {
  const window = new BrowserWindow({
    width: 1280,
    height: 860,
    minWidth: 960,
    minHeight: 640,
    title: 'RAG Query Engine',
    backgroundColor: '#0f172a',
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });
  mainWindow = window;

  window.once('ready-to-show', () => window.show());

  window.webContents.setWindowOpenHandler(({ url }) => {
    try {
      const parsed = new URL(url);
      if (parsed.protocol === 'https:' || parsed.protocol === 'mailto:') {
        shell.openExternal(parsed.toString());
      }
    } catch {
      // Block malformed external URLs.
    }
    return { action: 'deny' };
  });

  window.webContents.on('before-input-event', (event, input) => {
    if (!isDev && input.key === 'F12') event.preventDefault();
  });

  window.webContents.on('devtools-opened', () => {
    if (!isDev && process.env.RAG_ENABLE_DEVTOOLS !== 'true') {
      window.webContents.closeDevTools();
    }
  });

  window.webContents.on('will-navigate', (event, url) => {
    const allowed = url.startsWith(`${APP_PROTOCOL}://local`) || (isDev && url.startsWith(devAppUrl));
    if (!allowed) event.preventDefault();
  });

  window.loadURL(getAppUrl());
}

function scheduleUpdateChecks() {
  if (isDev || !autoUpdater || process.env.RAG_ENABLE_UPDATES === 'false') return;

  autoUpdater.autoDownload = false;
  autoUpdater.on('error', (error) => {
    console.error(`Update check failed: ${error.message}`);
  });
  setTimeout(() => {
    autoUpdater.checkForUpdates().catch((error) => {
      console.error(`Update check failed: ${error.message}`);
    });
  }, 15000);
}

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.exit(0);
} else {
  app.on('second-instance', () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
  });

  app.whenReady().then(async () => {
    registerAppProtocol();
    registerApiProxy();
    session.defaultSession.setPermissionRequestHandler((_webContents, _permission, callback) => callback(false));
    try {
      await startBackend();
    } catch (error) {
      console.error(error);
    }
    createWindow();
    scheduleUpdateChecks();

    app.on('activate', () => {
      if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
      }
    });
  });
}

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('before-quit', stopBackend);
